spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/storage
        username: postgres
        driver-class-name: org.postgresql.Driver
        password: 123

logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.orm.jdbc.bind: trace

